config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get "web_templates/"=> "web_templates#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web_templates_controller.rb
class WebTemplatesController < ApplicationController
  def index
  	render layout: false
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_templates_helper.rb
module WebTemplatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FodaFyp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_templates/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FODA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>

<div>
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Step 1: Choose Template</div>
        </div>
        <div class="clearfix">
        </div>
    </div>
<br/>

  <div class="col-lg-12 col-lg-offset-1"  >
      <div class="col-lg-6">
          <div class="member-team">
              <h3  style="text-align:center">KAdmin</h3>
          		<img id="a" style="height:278px;width:445px" src="/assets/kadmin.jpg" class="img-responsive"/>
              <div class="text-center pal">
                    <a href="http://foda-kadmin.thebucketdev.com/form_build" id="Demo3" class="btn btn-fill btn-info" data-button="info">Next</a>
              </div>
          </div>
      </div>

      <div class="col-lg-6">
          <div class="member-team">
              <h3  style="text-align:center">Lumino</h3>
              	<img id="a" style="height:278px;width:445px" src="/assets/lumino.jpg" class="img-responsive"/>
              <div class="text-center pal">
                    <a href="http://foda-lumino.thebucketdev.com/form_build" id="Demo3" class="btn btn-fill btn-info" data-button="info">Next</a>
              </div>
          </div>
      </div>
  </div>


</div>

<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/bootstrap-hover-dropdown.js"></script>

</body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/png" href="assets/img/favicon.ico">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>FODA</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />

        <link href="/assets/bootstrap.css" rel="stylesheet" />
        <link href="/assets/landing-page.css" rel="stylesheet"/>

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
        <link href="assets/pe-icon-7-stroke.css" rel="stylesheet" />

    </head>
    <body class="landing-page landing-page1">

            <nav class="navbar navbar-transparent navbar-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                    </button>
                    <a href="http://www.creative-tim.com">
                        <div class="logo-container">
                            <div class="logo">
                                <img src="assets/new_logo.png">
                            </div>
                            <div class="brand">
                                FYP 2016
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="example" >
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                            <i class="fa fa-facebook-square"></i>
                            Like
                            </a>
                        </li>
                        <li>
                            <a href="#">
                            <i class="fa fa-twitter"></i>
                            Tweet
                            </a>
                        </li>
                        <li>
                            <a href="#">
                            <i class="fa fa-pinterest"></i>
                            Pin
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>

        <div class="wrapper">
            <div class="parallax filter-gradient blue" data-color="blue">
                <div class="parallax-background">
                    <img class="parallax-background-image" src="assets/template/bg3.jpg">
                </div>
                <div class= "container">
                    <div class="row">
                        <div class="col-md-5 hidden-xs">
<!--                             <div class="parallax-image">
                                <img class="phone" src="assets/img/template/iphone3.png" style="margin-top: 20px"/>
                            </div> -->
                        </div>
                        <div class="col-md-12">
                            <div class="description">
                                <h2>FODA</h2>
                                <br>
                                <h5>What is FODA? FODA is a short form of feature oriented domain analysis. FODA is one of the methods in software development. This method focuses on decreasing the efforts in developing a software. With all requirements are store in one place the developer could choose features they wanted to add into the application. In this case, we are focusing on the Let's Go Application. This application is an event based application.</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-gray section-clients">
                <div class="container text-center">
                    <h4 class="header-text">Helps you in developing Apps & System</h4>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida ante a est pellentesque eleifend. Phasellus ac mollis lacus. Etiam et eros imperdiet, varius nisl sit amet, pretium elit. Integer quis condimentum diam, eu convallis leo. Aenean bibendum vitae nisl nec sagittis. Aenean mattis iaculis lectus, et pharetra ex euismod convallis. Morbi vel tincidunt eros.<br>
                    </p>
                </div>
            </div>
            <div class="section section-presentation">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="description">
                                <h4 class="header-text">Giving the Idea</h4>
                                <p>Maecenas malesuada eu nisi vel lobortis. Donec sagittis, velit euismod fringilla cursus, lacus lacus lobortis risus, eget laoreet tortor elit condimentum nibh. Phasellus nec risus posuere, aliquet mi pulvinar, dignissim quam. Mauris semper lectus sapien, accumsan laoreet risus rhoncus vitae. Donec at nulla faucibus, suscipit magna sed, vulputate neque. Maecenas congue tristique augue at pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. </p>
                                <p>Vestibulum magna massa, eleifend vel augue sit amet, sodales interdum velit. Nam quis lectus mattis, tincidunt eros sit amet, interdum felis. Sed et consectetur ipsum, at malesuada dolor. Sed vel velit in ex imperdiet condimentum in id arcu. Vestibulum eget tempor dui.
                                <p>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1 hidden-xs">
                            <img src="assets/template/mac.png"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-demo">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div id="description-carousel" class="carousel fade" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="item">
                                        <img src="assets/template/examples/home_33.jpg" alt="">
                                    </div>
                                    <div class="item active">
                                        <img src="assets/template/examples/home_22.jpg" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="assets/template/examples/home_11.jpg" alt="">
                                    </div>
                                </div>
                                <ol class="carousel-indicators carousel-indicators-blue">
                                    <li data-target="#description-carousel" data-slide-to="0" class=""></li>
                                    <li data-target="#description-carousel" data-slide-to="1" class="active"></li>
                                    <li data-target="#description-carousel" data-slide-to="2" class=""></li>
                                </ol>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <h4 class="header-text">Easy to integrate</h4>
                            <p>
                                With all the apps that users love! Make it easy for users to share, like, post and tweet their favourite things from the app. Be sure to let users know they continue to remain connected while using your app!
                            </p>
                            <a href="" id="Demo3" class="btn btn-fill btn-info" data-button="info">Mobile Apps Demo</a>
                            <a href="" id="http://foda-kadmin.thebucketdev.com" class="btn btn-fill btn-info" data-button="info">Web App Demo</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-features">
                <div class="container">
                    <h4 class="header-text text-center">Current Platforms</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i><img src="assets/android.png" style="height:63px;width:63px"></i>
                                </div>
                                <div class="text">
                                    <h4>Android</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida ante a est pellentesque eleifend. Phasellus ac mollis lacus.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i><img src="assets/ios.png" style="height:63px;width:63px"></i>
                                </div>
                                <h4>IOS</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida ante a est pellentesque eleifend. Phasellus ac mollis lacus.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i><img src="assets/chrome.png" style="height:63px;width:63px"></i>
                                </div>
                                <h4>Web Browser</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida ante a est pellentesque eleifend. Phasellus ac mollis lacus.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-no-padding">
                <div class="parallax filter-gradient blue" data-color="blue">
                    <div class="parallax-background">
                        <img class ="parallax-background-image" src="assets/template/bg3.jpg"/>
                    </div>
                    <div class="info">
                        <h1>Try out the FODA for free!</h1>
                        <p>Make Your Life Easier</p>
                        <a href="" class="btn btn-neutral btn-lg btn-fill">Mobile App</a>
                        <a href="<%= web_templates_path %>" class="btn btn-neutral btn-lg btn-fill">Web App</a>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <div class="social-area pull-right">
                        <a class="btn btn-social btn-facebook btn-simple">
                        <i class="fa fa-facebook-square"></i>
                        </a>
                        <a class="btn btn-social btn-twitter btn-simple">
                        <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-social btn-pinterest btn-simple">
                        <i class="fa fa-pinterest"></i>
                        </a>
                    </div>
                    <div class="copyright">
                        &copy; FYP 2016 <a href="">KICT</a>, made with love
                    </div>
                </div>
            </footer>
        </div>

    </body>
    <script src="assets/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="assets/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
    <script src="assets/bootstrap.js" type="text/javascript"></script>
    <script src="assets/awesome-landing-page.js" type="text/javascript"></script>
</html>